sudo: required
services:
  - docker

before_install:
  - docker build -t a2ron44/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -t a2ron44/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "a2ron44-docker"
  env: "A2ron44Docker-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-807638837950"
  bucket_path: "a2ron44-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
